In [3]:
import numpy as np

In [6]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [1]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x) # x와 형상이 같은 배열 생성
    
    for idx in range(x.size):
        tmp_val = x[idx]
        
        # f(x+h) 계산
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        # f(x-h) 계산
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        
    return grad

numerical_gradient(f, x) 함수의 인수인 f는 함수이고 x는 넘파이 배열이므로 넘파이 배열 x의 각 원소에 대해서 수치 미분을 구합니다.
그러면 이 함수를 사용해서 실제로 기울기를 계산해봅시다.
세 점 (3, 4), (2, 0), (3, 0)의 기울기를 구해보겠습니다.

In [7]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([ 6.,  8.])

In [8]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([ 0.,  4.])

In [9]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([ 6.,  0.])